import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "./components/navbar";
import { UserProvider } from "./login/context/userContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Klinik Pintar | AI Report Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body className={`${inter.className} antialiased`}>
        <ToastContainer />
        <div className="h-screen overflow-hidden flex flex-col bg-white">
          <UserProvider>
            {children}
          </UserProvider>
        </div>
      </body>
    </html>
  );
}
