services:
  db_postgre:
    build:
      dockerfile: Dockerfile.local
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-ai-report}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://db_sonarqube:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    networks:
      - sonarqube
    depends_on:
      - db_sonarqube

  db_sonarqube:
    image: postgres:latest
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_data:/var/lib/postgresql/data
    networks:
      - sonarqube

volumes:
  postgres_data:
    driver: local
  sonarqube_data:
    driver: local

networks:
  sonarqube:
    driver: bridge
