import { generateReportContent } from "@/app/(backend)/utils/generateReportContent";

describe("generateReportContent", () => {
  const mockData = {
    title: "Judul",
    content: "Isi laporan",
    createdAt: "2025-04-07T10:00:00.000Z"
  };

  it("should return markdown-like structured content", () => {
    const result = generateReportContent(mockData);
    expect(result).toContain("# Judul");
    expect(result).toContain("Isi laporan");
    expect(result).toContain("Generated by AI Report Generator");
  });

  it("should format the date correctly", () => {
    const result = generateReportContent(mockData);
    expect(result).toContain("7 April 2025");
  });
});