import { generateReportContent } from "@/app/(backend)/utils/generateReportContent";

describe("generateReportContent", () => {
  const mockData = {
    title: "Judul",
    content: "Isi laporan",
    createdAt: "2025-04-07T10:00:00.000Z"
  };

  it("should return markdown-like structured content", () => {
    const result = generateReportContent(mockData);
    expect(result).toContain("Isi laporan");
    expect(result).toContain("Generated by AI Report Generator");
  });

  it("should slice content starting from '**Laporan Analisis' if found", () => {
    const dataWithHeading = {
      title: "Test",
      content: "Beberapa kalimat pembuka...\n**Laporan Analisis** Bagian penting",
      createdAt: "2025-04-07T10:00:00.000Z"
    };
  
    const result = generateReportContent(dataWithHeading);
  
    // Harus dimulai dari heading, artinya bagian awal dibuang
    expect(result).toContain("**Laporan Analisis**");
    expect(result).not.toContain("Beberapa kalimat pembuka");
  });  
});