import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";
import Dropdown from "./components/dropdown";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen overflow-hidden flex flex-col bg-white">
          <Navbar />
          <div className="flex flex-1">
            <Sidebar />
            <main className="flex-1">
              <div className="max-w-[1200px] w-full mx-auto px-6">
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
