import React from "react";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";
import { ServiceProvider } from "./context/serviceContext";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <ServiceProvider>
          <div className="h-screen overflow-hidden flex flex-col bg-white">
            <Navbar />
            <div className="flex flex-1">
              <Sidebar />
              <main className="flex-1">
                <div className="max-w-[1200px] w-full mx-auto px-6">{children}</div>
              </main>
            </div>
          </div>
        </ServiceProvider>
      </body>
    </html>
  );
}
