import { ReportDTO } from "@/app/(backend)/dtos/report.dto";

export function generateReportContent(data: ReportDTO): string {
  const startIndex = data.content.indexOf("**Laporan Analisis");
  const cleanContent =
    startIndex !== -1 ? data.content.slice(startIndex) : data.content;

  return `${cleanContent}

Generated by AI Report Generator`;
}