import { ReportDTO } from "@/app/(backend)/dtos/report.dto";

export function generateReportContent(data: ReportDTO): string {
  const lineWidth = 120;
  const startIndex = data.content.indexOf("**Laporan Analisis");
  const cleanContent =
    startIndex !== -1 ? data.content.slice(startIndex) : data.content;

  const centerText = (text: string) => {
    const spaces = Math.max(0, Math.floor((lineWidth - text.length) / 2));
    return " ".repeat(spaces) + text;
  };

  const footer = centerText("Generated by AI Report Generator");

  return `${cleanContent}

${footer}`;
}