import { ReportDTO } from "@/app/(backend)/dtos/report.dto";

export function generateReportContent(data: ReportDTO): string {
  return `# ${data.title}
  
Created at: ${new Date(data.createdAt).toLocaleDateString("id-ID", {
  day: "numeric",
  month: "long",
  year: "numeric"
})}

---

${data.content}

Generated by AI Report Generator`;
}